- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Remove old Docker packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker.io
    - docker-engine

- name: Docker APT key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker APT repo
  apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker package
  apt:
    name: docker-ce
    state: present

- name: Prevent automatic upgrades to Docker
  dpkg_selections:
    name: docker-ce
    selection: hold

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
    checksum: "{{ docker_compose_checksum }}"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755
