- name: Intel microcode
  apt:
    pkg: intel-microcode
    state: latest
  when: ansible_distribution_release == "Ubuntu" and ansible_virtualization_role != "guest" and ansible_processor[1] == "GenuineIntel"

- name: VMware Tools
  apt:
    pkg: open-vm-tools
    state: latest
  when: ansible_pkg_mgr == "apt" and ansible_virtualization_role == "guest" and ansible_virtualization_type == "VMware"
