- name: Intel microcode
  apt:
    pkg: intel-microcode
    state: latest
  when: ansible_distribution == "Ubuntu" and ansible_virtualization_role is defined and ansible_virtualization_role != "guest" and ansible_processor[1] == "GenuineIntel"

- name: AMD64 microcode
  apt:
    pkg: amd64-microcode
    state: latest
  when: ansible_distribution == "Ubuntu" and ansible_virtualization_role is defined and ansible_virtualization_role != "guest" and ansible_processor[1] == "AuthenticAMD"

- name: VMware Tools
  apt:
    pkg: open-vm-tools
    state: latest
  when: ansible_pkg_mgr == "apt" and and ansible_virtualization_role is defined ansible_virtualization_role == "guest" and and ansible_virtualization_type is defined ansible_virtualization_type == "VMware"
